### ISSUE TITLE
Samsung 990 Pro incorrect output

### ISSUE THREAD

**Issue by pdmahon1** [aattwwss/ssd-bot-go#12]
Today, the SSD Bot posted incorrect stats for the 2TB version of the Samsung 990 Pro. It output 1GB DRAM instead, which is for the 1TB model. The 2TB model should output 2GB DRAM.

Here is the comment left by the bot: [Direct Link](https://www.reddit.com/r/buildapcsales/comments/14wtgj1/ssd_samsung_990_pro_2tb_pcie_gen4_x4_nvme_20c/jrjphka/)

**Comment by aattwwss** [comment]
Yup am aware of the issues. Currently I don't have a good way to search by the capacity.

**Comment by aattwwss** [comment]
https://github.com/aattwwss/ssd-bot-go/pull/18
